##tomcat
server:
  port: 8886

spring:
  ##数据库
  datasource:
    url: jdbc:mysql://localhost:3306/pg_performancesy?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ##安全机制
  security:
    user:
      name: admin
      password: 123
  ##thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  ##开启热部署
  devtools:
    restart:
      enabled: true

